### ISSUE TITLE
Error when enabling after disable

### ISSUE THREAD

**Issue by ErikHommel** [systopia/de.systopia.identitytracker#5]
If I disable the extension and then enable again I get this error:
```
CiviCRM_API3_Exception: "DB Error: already exists"

#0 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(190): civicrm_api3("Extension", "install", (Array:2))
#1 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(466): CRM_Admin_Form_Extensions->postProcess()
#2 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#3 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#4 /var/web/vd10659/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#5 /var/web/vd10659/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#6 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#7 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#8 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(1, NULL)
#9 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#10 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#11 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:16))
#12 /var/web/vd10659/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /var/web/vd10659/public_html/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#14 /var/web/vd10659/public_html/includes/menu.inc(527): civicrm_invoke("admin", "extensions")
#15 /var/web/vd10659/public_html/index.php(21): menu_execute_active_handler()
#16 {main}
```

**Comment by jensschuppe** [comment]
This should be fixed for long; most entities the extension tries to create when installing are now managed entities.
